name: "publish the package to npm"

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4  # Updated to v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2


      - name: install dependencies
        run: bun install

      - name: build project
        run: bun run build

      - name: publish to npm
        run: bun publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

